NameCodeType = {
    "01": "Proprietary",
    "06": "GLN",
    "16": "ISNI",  # international standard name identifier
    "36": "Nasjonalt Autoritetsregister",
}

NotificationType = {
    "01": "Early notification",      # registered, not controlled
    "02": "Advance notification",    # controlled
    "03": "Notification confirmed",  # controlled and complete
    "05": "Delete",                  # record MUST be deleted
    "Notification confirmed": "Notification confirmed"
}

ProductIdentifierCode = {
    "01": "Proprietary",
    "03": "GTIN-13/EAN",
    "06": "Digital Object Identifier",
    "15": "ISBN-13",
    "25": "ISMN-13"
}

ProductComposition = {
    "00": "Single-Item-Retail-Product",
    "10": "Multi-Item-Product",
    "20": "Trade-Only-Product"
}

ProductForm = {
    "AB": "Audio-Cassette",
    "AC": "CD Audio",
    "AF": "Audio Tape",
    "AJ": "Downloadable Audio File",
    "AK": "Prerecorded Digital Audio Player",
    "BB": "Hardback",
    "Hardback": "Hardback",
    "BC": "Paperback",
    "BD": "Loose-leaf",
    "BE": "Spiral-bound",
    "BH": "Board Book",
    "BL": "Slide Bound",
    "CB": "Sheep Map, folded",
    "CD": "Sheet Map, rolled",
    "CE": "Globe",
    "DB": "CD-Rom",
    "DF": "Diskette",
    "DI": "DVD-Rom",
    "DZ": "Other Digital Carrier",
    "EB": "Digital Content Available Both By Download and By Online Access",
    "ED": "Digital download",
    "FA": "Slides",
    "FD": "OHP transparencies for overhead projector",
    "PA": "Miscellaneous prints",
    "PC": "Calendar",
    "PD": "Cards",
    "PF": "Diary",
    "PJ": "Postcard or book",
    "PK": "Poster",
    "PM": "Wallet or folder",
    "PO": "Wall Chart",
    "PR": "Note book / blank book",
    "PZ": "Other printed item",
    "SA": "Multiple-item retail product",
    "VA": "Video, detail unspecified",
    "VI": "DVD-video",
    "VO": "Blu Ray",
    "XE": "Counterpack filled",
    "XM": "Boxed pack",
    "ZA": "General Merchandise",
    "ZC": "Soft Toy",
    "ZD": "Toy",
    "ZE": "Game",
    "ZG": "E-book reader",
    "ZI": "Audiobook player",
    "ZJ": "Jigzaw",
    "ZL": "Tote bag",
    "ZM": "Tableware",
    "ZN": "Umbrella",
    "ZY": "Other apparel",
    "ZZ": "Other merchandise",
    "00": "Undefined"
}

ProductFormDetail = {
    "A103": "MP3 Format",
    "A106": "WMA",
    "B113": "Pocket (Sweden/Norway)",
    "B301": "Loose leaf - sheets and binder",
    "B303": "Loose leaf - sheets only",
    "B208": "Sound story/Boisy book",
    "B209": "Sticker book",
    "B210": "Touch and feel book",
    "B202": "Lift the flap book",
    "B404": "Leather, imitation",
    "B403": "Leather, real",
    "B409": "Cloth",
    "B413": "Plastic covered",
    "D105": "MPEG-4",
    "E101": "EPUB",
    "E107": "PDF",
    "E144": "EBP",
    "E201": "Fixed Format",
    "E210": "Landscape",
    "E211": "Portrait"
}

ProductFormFeature = {
    "01": "Color of cover",
    "02": "Color of page edge",
    "03": "Text font",
    "04": "Special cover material",
    "06": "Operating system requirements",
    "07": "Other system requirements",
    "15": "E-publication format version code",
    "18": "E-publication authentication and access control"
}

ProductFormFeatureValueColor = {
    "BLK": "Black",
    "BLU": "Blue",
    "BRN": "Brown",
    "BUR": "Burgundy/maroon",
    "GLD": "Gold",
    "GRN": "Green",
    "GRY": "Grey",
    "ORG": "Orange",
    "PNK": "Pink",
    "PUR": "Purple",
    "RED": "Red",
    "SLV": "Silver",
    "TAN": "Tan",
    "TEA": "Teal/turquoise green",
    "WHI": "White",
    "YEL": "Yellow",
}

ProductFormFeatureValueEpubNo = {
    "101A": "Epub 2.0.1",
    "101B": "Epub 3.0",
}

ProductFormFeatureValueOS = {
    "01": "Android",
    "02": "Blackberry OS",
    "03": "iOS",
    "04": "Linux",
    "07": "Palm OS",
    "09": "Symbian",
    "10": "Widnows",
    "11": "Windows CE",
    "12": "Windows mobile",
    "13": "Mac OS",
    "14": "Windows Phone 7",
}

ProductFormFeatureValueSysReq = {
    "Smart Bok": "Smart bok",
    "Smart Øving": "Smart øving",
    "Smart Vurdering": "Smart vurdering",
    "Unibok": "Unibok",
    "D-bok": "D-bok",
    "Brettbok": "Brettbok",
    "Aunivers": "Aunivers",
    "Lokus": "Lokus"
}

ProductFormFeatureValueEpubDetails = {
    "02": "Accessibility Specification 1.0 A",
    "03": "Accessibility Specification 1.0 AA",
    "21": "Text-to-speech hinting provided",
    "24": "Dyslexia Readability"
}

ProductFormFeatureDescription = {
    "Feide": "Feide",
    "Bank-ID": "Bank-ID",
    "Proprietær": "Proprietary",
    "Bliss": "Symbol language",
    "Blokkbokstaver": "Capitals only",
    "Braille": "Braille",
    "Storskrift": "Large print",
    "Tegnspråk": "Sign language",
    "Widgit": "Symbol language"
}

EpubTechnicalProtection = {
    "00": "None",
    "02": "Digital Watermarking",
    "03": "Adobe RDM",
    "06": "Readium LCP DRM"
}

ProductClassificationType = {
    "07": "Sender Product Category"
}

ProductClassificationCode = {
    "NKR_JA": "Included in Norwegian arts council purhcasing scheme for public libraries",
    "NKR_NEI": "Not included in Norwegian arts council purchasing scheme for public libraries",
    "Bok": "Book",
    "Vare": "Non-book",
    "Film": "Movie",
    "Musikk": "Music",
    "INT_BOOK": "International e-book publisher"
}

CollectionType = {
    "10": "Publisher Collection",
    "20": "Ascribed Collection"
}

CollectionIDType = {
    "01": "Proprietary"
}

TitleTypeCode = {
    "01": "Distinctive title",
    "03": "Title in original language",
    "11": "Alternative title on cover",
    "Distinctive title": "Distinctive title"
}

TitleElementLevel = {
    "01": "Product",          # individual product
    "02": "Collection Level"  # top level of bibliographical collection
}

ContributorRoleCode = {
    "A01": "Author of book",
    "A03": "Author of screenplay",
    "A06": "Author of composition",
    "A07": "Artist",
    "A09": "Created by",
    "A10": "From an idea by",
    "A12": "Illustrated by",
    "A13": "Photographs by",
    "A32": "Contributions by",
    "A38": "Original author",
    "A99": "Other primary creator",
    "B01": "Edited by",
    "B06": "Translated by",
    "B20": "Consultant Editor",
    "D01": "Producer",
    "D02": "Director",
    "E01": "Actor",
    "E05": "Voval soloist",
    "E06": "Instrumental Soloist",
    "E07": "Read by",
    "Z02": "Honored/dedicated to",
    "Z03": "Enacting Jurisdiction",
    "Z99": "Other",
    "Author of book": "Author of book"
}

PersonNameType = {
    "01": "Pseudonym",
    "02": "Authority controlled name",
    "04": "Real name",
    "07": "Fictional Name",
    "Real name": "Real name"
}

PersonDateRole = {
    "50": "Date of birth",
    "51": "Date of death"
}

DateFormat = {
    "00": "YYYYMMDD",
    "05": "YYYY",
    "13": "YYYYMMDDThhmm",
    "14": "YYYYMMDDThhmmss"
}

ContributorPlaceRelatorCode = {
    "01": "Born in"
}

CountryCode = {
    "AD": "Andorra",
    "AE": "United Arab Emirates",
    "AF": "Afghanistan",
    "AG": "Antigua and Barbuda",
    "AI": "Anguilla",
    "AL": "Albania",
    "AM": "Armenia",
    "AN": "Netherlands Antilles",
    "AO": "Angola",
    "AQ": "Antarctica",
    "AR": "Argentina",
    "AS": "American Samoa",
    "AT": "Austria",
    "AU": "Australia",
    "AW": "Aruba",
    "AX": "Åland Islands",
    "AZ": "Azerbaijan",
    "BA": "Bosnia and Herzegovina",
    "BB": "Barbados",
    "BD": "Bangladesh",
    "BE": "Belgium",
    "BF": "Burkina Faso",
    "BG": "Bulgaria",
    "BH": "Bahrain",
    "BI": "Burundi",
    "BJ": "Benin",
    "BL": "Saint Barthélemy",
    "BM": "Bermuda",
    "BN": "Brunei Darussalam",
    "BO": "Bolivia, Plurinational State of",
    "BQ": "Bonaire, Sint Eustatius and Saba",
    "BR": "Brazil",
    "BS": "Bahamas",
    "BT": "Bhutan",
    "BV": "Bouvet Island",
    "BW": "Botswana",
    "BY": "Belarus",
    "BZ": "Belize",
    "CA": "Canada",
    "CC": "Cocos (Keeling) Islands",
    "CD": "Congo, Democratic Republic of the",
    "CF": "Central African Republic",
    "CG": "Congo",
    "CH": "Switzerland",
    "CI": "Cote d’Ivoire",
    "CK": "Cook Islands",
    "CL": "Chile",
    "CM": "Cameroon",
    "CN": "China",
    "CO": "Colombia",
    "CR": "Costa Rica",
    "CS": "Serbia and Montenegro",
    "CU": "Cuba",
    "CV": "Cabo Verde",
    "CW": "Curaçao",
    "CX": "Christmas Island",
    "CY": "Cyprus",
    "CZ": "Czech Republic",
    "DE": "Germany",
    "DJ": "Djibouti",
    "DK": "Denmark",
    "DM": "Dominica",
    "DO": "Dominican Republic",
    "DZ": "Algeria",
    "EC": "Ecuador",
    "EE": "Estonia",
    "EG": "Egypt",
    "EH": "Western Sahara",
    "ER": "Eritrea",
    "ES": "Spain",
    "ET": "Ethiopia",
    "FI": "Finland",
    "FJ": "Fiji",
    "FK": "Falkland Islands (Malvinas)",
    "FM": "Micronesia, Federated States of",
    "FO": "Faroe Islands",
    "FR": "France",
    "GA": "Gabon",
    "GB": "United Kingdom",
    "GD": "Grenada",
    "GE": "Georgia",
    "GF": "French Guiana",
    "GG": "Guernsey",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GL": "Greenland",
    "GM": "Gambia",
    "GN": "Guinea",
    "GP": "Guadeloupe",
    "GQ": "Equatorial Guinea",
    "GR": "Greece",
    "GS": "South Georgia and the South Sandwich Islands",
    "GT": "Guatemala",
    "GU": "Guam",
    "GW": "Guinea-Bissau",
    "GY": "Guyana",
    "HK": "Hong Kong",
    "HM": "Heard Island and McDonald Islands",
    "HN": "Honduras",
    "HR": "Croatia",
    "HT": "Haiti",
    "HU": "Hungary",
    "ID": "Indonesia",
    "IE": "Ireland",
    "IL": "Israel",
    "IM": "Isle of Man",
    "IN": "India",
    "IO": "British Indian Ocean Territory",
    "IQ": "Iraq",
    "IR": "Iran, Islamic Republic of",
    "IS": "Iceland",
    "IT": "Italy",
    "JE": "Jersey",
    "JM": "Jamaica",
    "JO": "Jordan",
    "JP": "Japan",
    "KE": "Kenya",
    "KG": "Kyrgyzstan",
    "KH": "Cambodia",
    "KI": "Kiribati",
    "KM": "Comoros",
    "KN": "Saint Kitts and Nevis",
    "KP": "Korea, Democratic People’s Republic of",
    "KR": "Korea, Republic of",
    "KW": "Kuwait",
    "KY": "Cayman Islands",
    "KZ": "Kazakhstan",
    "LA": "Lao People’s Democratic Republic",
    "LB": "Lebanon",
    "LC": "Saint Lucia",
    "LI": "Liechtenstein",
    "LK": "Sri Lanka",
    "LR": "Liberia",
    "LS": "Lesotho",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "LV": "Latvia",
    "LY": "Libya",
    "MA": "Morocco",
    "MC": "Monaco",
    "MD": "Moldova, Repubic of",
    "ME": "Montenegro",
    "MF": "Saint Martin (French part)",
    "MG": "Madagascar",
    "MH": "Marshall Islands",
    "MK": "Macedonia, the former Yugoslav Republic of",
    "ML": "Mali",
    "MM": "Myanmar",
    "MN": "Mongolia",
    "MO": "Macao",
    "MP": "Northern Mariana Islands",
    "MQ": "Martinique",
    "MR": "Mauritania",
    "MS": "Montserrat",
    "MT": "Malta",
    "MU": "Mauritius",
    "MV": "Maldives",
    "MW": "Malawi",
    "MX": "Mexico",
    "MY": "Malaysia",
    "MZ": "Mozambique",
    "NA": "Namibia",
    "NC": "New Caledonia",
    "NE": "Niger",
    "NF": "Norfolk Island",
    "NG": "Nigeria",
    "NI": "Nicaragua",
    "NL": "Netherlands",
    "NO": "Norway",
    "NP": "Nepal",
    "NR": "Nauru",
    "NU": "Niue",
    "NZ": "New Zealand",
    "OM": "Oman",
    "PA": "Panama",
    "PE": "Peru",
    "PF": "French Polynesia",
    "PG": "Papua New Guinea",
    "PH": "Philippines",
    "PK": "Pakistan",
    "PL": "Poland",
    "PM": "Saint Pierre and Miquelon",
    "PN": "Pitcairn",
    "PR": "Puerto Rico",
    "PS": "Palestine, State of",
    "PT": "Portugal",
    "PW": "Palau",
    "PY": "Paraguay",
    "QA": "Qatar",
    "RE": "Réunion",
    "RO": "Romania",
    "RS": "Serbia",
    "RU": "Russian Federation",
    "RW": "Rwanda",
    "SA": "Saudi Arabia",
    "SB": "Solomon Islands",
    "SC": "Seychelles",
    "SD": "Sudan",
    "SE": "Sweden",
    "SG": "Singapore",
    "SH": "Saint Helena, Ascension and Tristan da Cunha",
    "SI": "Slovenia",
    "SJ": "Svalbard and Jan Mayen",
    "SK": "Slovakia",
    "SL": "Sierra Leone",
    "SM": "San Marino",
    "SN": "Senegal",
    "SO": "Somalia",
    "SR": "Suriname",
    "SS": "South Sudan",
    "ST": "Sao Tome and Principe",
    "SV": "El Salvador",
    "SX": "Sint Maarten (Dutch part)",
    "SY": "Syrian Arab Republic",
    "SZ": "Swaziland",
    "TC": "Turks and Caicos Islands",
    "TD": "Chad",
    "TF": "French Southern Territories",
    "TG": "Togo",
    "TH": "Thailand",
    "TJ": "Tajikistan",
    "TK": "Tokelau",
    "TL": "Timor-Leste",
    "TM": "Turkmenistan",
    "TN": "Tunisia",
    "TO": "Tonga",
    "TR": "Turkey",
    "TT": "Trinidad and Tobago",
    "TV": "Tuvalu",
    "TW": "Taiwan, Province of China",
    "TZ": "Tanzania, United Republic of",
    "UA": "Ukraine",
    "UG": "Uganda",
    "UM": "United States Minor Outlying Islands",
    "US": "United States",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VA": "Holy See (Vatican City State)",
    "VC": "Saint Vincent and the Grenadines",
    "VE": "Venezuela, Bolivarian Republic of",
    "VG": "Virgin Islands, British",
    "VI": "Virgin Islands, US",
    "VN": "Viet Nam",
    "VU": "Vanuatu",
    "WF": "Wallis and Futuna",
    "WS": "Samoa",
    "YE": "Yemen",
    "YT": "Mayotte",
    "YU": "Yugoslavia",
    "ZA": "South Africa",
    "ZM": "Zambia",
    "ZW": "Zimbabwe",
}

LanguageCode = {
    "01": "Language of text",
    "02": "Original language of a translated text"
}

Language = {
    "afr": "Afrikaans",
    "alb": "Albanian",
    "amh": "Amharic",
    "ara": "Arabic",
    "ben": "Bengali",
    "bos": "Bosnian",
    "bul": "Bulgarian",
    "bur": "Burmese",
    "cat": "Catalan",
    "ckb": "Central Kurdish (Sorani)",
    "chi": "Chinese",
    "cze": "Czech",
    "dan": "Danish",
    "dut": "Dutch; Flemish",
    "eng": "English",
    "epo": "Esperanto",
    "est": "Estonian",
    "fao": "Faroese",
    "fij": "Fijian",
    "fin": "Finnish",
    "fkv": "Kvensk",
    "fre": "French",
    "ger": "German",
    "gla": "Scottish Gaelic",
    "gle": "Irish",
    "grc": "Greek, Ancient (to 1453)",
    "gre": "Grekk, Modern (1453-)",
    "heb": "Hebrew",
    "hin": "Hindi",
    "hrv": "Croatian",
    "hun": "Hungarian",
    "ice": "Icelandic",
    "ind": "Indonesian",
    "ita": "Italian",
    "jpn": "Japanese",
    "kor": "Korean",
    "kur": "Kurdish",
    "lao": "Lao",
    "lat": "Latin",
    "lit": "Lithuanian",
    "mac": "Macedonian",
    "mnk": "Mandingo",
    "mon": "Mongolian",
    "mul": "Multiple languages",
    "nno": "Norwegian Nynorsk",
    "nob": "Norwegian Bokmål",
    "nor": "Norwegian Bokmål",
    "non": "Old Norse",
    "per": "Persian; Farsi",
    "pol": "Polish",
    "por": "Portugese",
    "pus": "Pashto",
    "rum": "Romanian",
    "rus": "Russian",
    "sin": "Sinhalese ; Sinhala",
    "slo": "Slovak",
    "slv": "Slovenian",
    "sma": "Southern Sami",
    "sme": "Northern Sami",
    "smi": "Sami languages",
    "smj": "Lule Sami",
    "smn": "Inari Sami",
    "sms": "Skolt Sami",
    "som": "Somali",
    "spa": "Spanish",
    "srp": "Serbian",
    "swa": "Swahili",
    "swe": "Swedish",
    "tam": "Tamil",
    "tgl": "Tagalog",
    "tha": "Thai",
    "tib": "Tibetan",
    "tir": "Tigrinya",
    "tkl": "Tokelauan",
    "tur": "Turkish",
    "ukr": "Ukranian",
    "urd": "Urdu",
    "vie": "Vietnamese",
    "san": "san",
    "man": "man",
    "prs": "prs",
    "may": "may",
    "kar": "kar",
    "rom": "rom"
}

ExtentTypeCode = {
    "00": "Main content page count",
    "08": "Number of pages in print count",
    "09": "Duration",
    "22": "Filesize"
}

ExtentUnit = {
    "03": "Pages",
    "05": "minutes",
    "15": "Hours and minutes HHHMM",
    "16": "Hours minutes seconds HHHMMSS",
    "17": "Bytes"
}

SubjectSchemeIdentifierCode = {
    "24": "Proprietary subject scheme",
    "37": "Bokgrupper",
    "38": "Varegrupper",
    "43": "Utdanningsprogram",
    "44": "Programområde",
    "45": "Undervisningsmateriell",
    "46": "Norsk DDK",
    "60": "Fagkoder",
    "93": "Thema Subject Category",
    "94": "Thema Geographical qualifier",
    "95": "Thema Language Qualifier",
    "96": "Thema time period qualifier",
    "97": "Thema educational purpose qualifier",
    "98": "Thema interest age / special interest qualifier",
    "99": "Thema style qualifier"
}

Bokgrupper = {
    "110": "Grunnskolen",
    "120": "Videregående skole",
    "211": "Jus",
    "212": "Økonomi, administrasjon og markedsføring",
    "213": "Helse og sosialfag",
    "214": "Samfunnsvitenskapelige fag",
    "215": "Pedagogikk",
    "216": "Språk og estetiske fag",
    "217": "Religion, historie, litteraturvitenskap, filosofi",
    "218": "Tekniske fag",
    "219": "Naturvitenskapelige fag",
    "210": "Diverse",
    "221": "Jus",
    "222": "Økonomi, administrasjon og markedsføring",
    "223": "Helse og sosialfag",
    "224": "Samfunnsvitenskapelige fag",
    "225": "Pedagogikk",
    "226": "Språk og estetiske fag",
    "227": "Religion, historie, litteraturvitenskap, filosofi",
    "228": "Tekniske fag",
    "229": "Naturvitenskapelige fag",
    "220": "Diverse",
    "311": "Kultur, religion, kunst",
    "312": "Samfunn, historie",
    "313": "Kropp og sinn",
    "314": "Natur, friluftsliv, sport",
    "315": "Reise og geografi",
    "316": "Mat og drikke",
    "317": "Hobby",
    "318": "Teknikk og populærvitenskap",
    "319": "Memoarer, biografier",
    "310": "Diverse",
    "321": "Kultur, religion, kunst",
    "322": "Samfunn, historie",
    "323": "Kropp og sinn",
    "324": "Natur, friluftsliv, sport",
    "325": "Reise og geografi",
    "326": "Mat og drikke",
    "327": "Hobby",
    "328": "Teknikk og populærvitenskap",
    "329": "Memoarer, biografier",
    "320": "Diverse",
    "331": "Billedbøker",
    "332": "Barn",
    "333": "Junior",
    "334": "Ungdom",
    "330": "Diverse",
    "341": "Billedbøker",
    "342": "Barn",
    "343": "Junior",
    "344": "Ungdom",
    "340": "Diverse",
    "411": "Romaner",
    "412": "Noveller",
    "413": "Lyrikk",
    "414": "Skuespill",
    "415": "Essays",
    "416": "Antologier",
    "417": "Krim/spenning",
    "418": "Klassisk litteratur",
    "419": "Sang- og visebøker",
    "410": "Diverse",
    "421": "Romaner",
    "422": "Noveller",
    "423": "Lyrikk",
    "424": "Skuespill",
    "425": "Essays",
    "426": "Antologier",
    "427": "Krim/spenning",
    "428": "Klassisk litteratur",
    "429": "Sang- og visebøker",
    "420": "Diverse",
    "431": "Billedbøker",
    "432": "Romaner barn",
    "433": "Romaner junior",
    "434": "Romaner ungdom",
    "435": "Antologier",
    "436": "Klassisk litteratur",
    "437": "Sang, viser, dikt",
    "438": "Noveller",
    "430": "Diverse",
    "441": "Billedbøker",
    "442": "Romaner barn",
    "443": "Romaner junior",
    "444": "Romaner ungdom",
    "445": "Antologier",
    "446": "Klassisk litteratur",
    "447": "Sang, viser, dikt",
    "448": "Noveller",
    "440": "Diverse",
    "501": "Norsk sakprosa for voksne",
    "502": "Norsk skjønnlitteratur for voksne",
    "503": "Oversatt sakprosa for voksne",
    "504": "Oversatt skjønnlitteratur for voksne",
    "505": "Norsk sakprose for barn og ungdom",
    "506": "Norsk skjønnlitteratur for barn og ungdom",
    "507": "Oversatt sakprosa for barn og ungdom",
    "508": "Oversatt skjønnlitteratur for barn og ungdom",
    "500": "Diverse",
    "601": "Skjønnlitterære verk for voksne",
    "602": "Sakprosaverk for voksne",
    "603": "skjønnlitterære verk for barn og unge",
    "604": "Sakprosaverk for barn og unge",
    "605": "Leksikale verk for voksne",
    "606": "Leksikale verk for barn og unge",
    "600": "Diverse",
    "701": "Tidsskrifter",
    "702": "Grunnskolen/Videregående skole",
    "703": "Lærebøker for høyere utdanning",
    "704": "Lærebøker til voksenopplæring",
    "705": "Fagbøker for profesjonsmarkedet",
    "706": "Skjønnlitteratur/sakprosa for voksne",
    "707": "Skjønnlitteratur/sakprosa for barn",
    "708": "Lover, forskrifter og forskningsrapporter",
    "709": "Sammensatte bokprodukter",
    "700": "Diverse",
    "801": "Grunnskolen",
    "802": "Videregående skole",
    "803": "Høyere utdanning",
    "804": "Voksenopplæring",
    "805": "Faglitteratur for profesjonsmarkedet",
    "806": "Sakprosa for voksne",
    "807": "Sakprosa for barn og unge",
    "808": "Skjønnlitteratur barn og unge",
    "809": "Lover, forskrifter og forskningsrapporter",
    "800": "Diverse",
    "811": "Norsk sakprosa for voksne",
    "812": "Norsk skjønnlitteratur for voksne",
    "813": "Oversatt sakprosa for voksne",
    "814": "Oversatt skjønnlitteratur for voksne",
    "815": "Norsk sakprosa for barn og ungdom",
    "816": "Norsk skjønnlitteratur for barn og ungdom",
    "817": "Oversatt sakprosa for barn og ungdom",
    "818": "Oversatt skjønnlitteratur for barn og ungdom",
    "810": "Diverse",
    "820": "Diverse",
    "821": "Grunnskolen",
    "822": "Videregående skole",
    "823": "Høyere utdanning",
    "824": "Voksenopplæring",
    "825": "Faglitteratur for profesjonsmarkedet",
    "831": "Kart",
    "832": "Kalendere, dagbøker, almanakker",
    "833": "Lover forskrifter og forskningsrapporter",
    "834": "Leker, puslespill, dokker, tegne- og malemateriell, tekstiler",
    "835": "Butikkmateriell",
    "836": "Kontorartikler og kortevarer",
    "837": "Vitnemål, skoleadministrativt materiell",
    "838": "Sammensatte produkter",
    "839": "Annet, video",
    "830": "Diverse",
    "840": "Kart",
    "841": "Kart",
    "851": "Norsk sakprosa, voksne",
    "852": "Norsk skjønnlitteratur, voksne",
    "853": "Oversatt sakprosa, voksne",
    "854": "Oversatt skjønnlitteratur, voksne",
    "855": "Norsk sakprosa, barn og unge",
    "856": "Norsk skjønnlitteratur, barn og unge",
    "857": "Oversatt sakprosa, barn og unge",
    "858": "Oversatt skjønnlitteratur, barn og unge",
    "850": "Diverse",
    "881": "Norsk sakprosa for voksne",
    "882": "Norsk skjønnlitteratur for voksne",
    "883": "Oversatt sakprosa for voksne",
    "884": "Oversatt skjønnlitteratur for voksne",
    "885": "Norsk sakprosa for barn og ungdom",
    "886": "Norsk skjønnlitteratur for barn og ungdom",
    "887": "Oversatt sakprosa for barn og ungdom",
    "888": "Oversatt skjønnlitteratur for barn og ungdom",
    "880": "Diverse",
    "891": "Grunnskolen",
    "892": "Videregående skole",
    "893": "Høyere utdanning",
    "894": "Voksenopplæring",
    "895": "Faglitteratur for profesjonsmarkedet",
    "890": "Diverse",
    "910": "Norske serieromaner",
    "920": "Oversatte underholdningsromaner",
    "931": "Sakprosa på originalspråket, voksen",
    "932": "Ordbøker og undervisningsmateriell på originalspråket",
    "933": "Reise og geografi på originalspråket",
    "934": "Sakprosa på originalspråket, barn og ungdom",
    "930": "Diverse",
    "941": "Skjønnlitteratur på originalspråket, voksen",
    "942": "Krim og spenning på originalspråket, voksen",
    "943": "Fantasy/SF på originalspråket, voksen",
    "944": "Skjønnlitteratur på originalspråket, barn og ungdom",
    "940": "Diverse"
}

Varegrupper = {
    "11000": "Grunnskole, diverse",
    "11001": "Grunnskole, diverse ebøker",
    "11002": "Grunnskole, diverse lydbøker",
    "11010": "Småskolen, 1-4 klasse",
    "11011": "Småskolen, 1-4 klasse ebøker",
    "11012": "Småskolen, 1-4 klasse lydbøker",
    "11020": "Mellomtrinn, 5-7 klasse",
    "11021": "Mellomtrinn, 5-7 klasse ebøker",
    "11022": "Mellomtrinn, 5-7 klasse lydbøker",
    "11030": "Ungdomstrinn, 8-10 klasse",
    "11031": "Ungdomstrinn, 8-10 klasse ebøker",
    "11032": "Ungdomstrinn, 8-10 klasse lydbøker",
    "12000": "Videregående skole, diverse",
    "12001": "Videregående skole, diverse ebøker",
    "12002": "Videregående skole, diverse lydbøker",
    "12010": "Videregående skole",
    "12011": "Videregående skole ebøker",
    "12012": "Videregående skole lydbøker",
    "12020": "Brukte bøker, brukes ikke av FS",
    "13000": "Opplæring for voksne innvandrere, diverse",
    "13001": "Opplæring for voksne innvandrere , diverse ebøker",
    "13002": "Opplæring for voksne innvandrere, diverse lydbøker",
    "13010": "Opplæring for voksne innvandrere",
    "13011": "Opplæring for voksne innvandrere ebøker",
    "13012": "Opplæring for voksne innvandrere lydbøker",
    "21000": "Jus, diverse",
    "21001": "Jus, diverse ebøker",
    "21002": "Jus, diverse lydbøker",
    "21010": "Jus",
    "21011": "Jus ebøker",
    "21012": "Jus lydbøker",
    "21020": "Kriminologi",
    "21021": "Kriminologi ebøker",
    "21022": "Kriminologi lydbøker",
    "21030": "Lover - særtrykk og forskrifter",
    "21031": "Lover - særtrykk og forskrifter ebøker",
    "21032": "Lover - særtrykk og forskrifter lydbøker",
    "21040": "Lover / lovsamlinger / kommentarutgaver",
    "21041": "Lover / lovsaml. / kommentarutg. ebøker",
    "21042": "Lover / lovsaml. / kommentarutg. lydbøker",
    "21090": "Jus tilbud",
    "21091": "Jus tilbud ebøker",
    "21092": "Jus tilbud lydbøker",
    "22000": "Økonomi / ledelse, diverse",
    "22001": "Økonomi / ledelse, diverse ebøker",
    "22002": "Økonomi / ledelse, diverse lydbøker",
    "22010": "Økonomi / regnskap / revisjon",
    "22011": "Økonomi / regnskap / revisjon ebøker",
    "22012": "Økonomi / regnskap / revisjon lydbøker",
    "22020": "Markedsføring",
    "22021": "Markedsføring ebøker",
    "22022": "Markedsføring lydbøker",
    "22030": "Organisasjon / ledelse / administrasjon",
    "22031": "Organisasjon / ledelse / admin. ebøker",
    "22032": "Organisasjon / ledelse / admin. lydbøker",
    "22040": "Sosialøkonomi",
    "22041": "Sosialøkonomi ebøker",
    "22042": "Sosialøkonomi lydbøker",
    "22090": "Økonomi / ledelse tilbud",
    "22091": "Økonomi/ledelse tilbud ebøker",
    "22092": "Økonomi/ledelse tilbud lydbøker",
    "23000": "Pedagogikk / psykologi,  diverse",
    "23001": "Pedagogikk / psykologi, diverse ebøker",
    "23002": "Pedagogikk / psykologi, diverse lydbøker",
    "23010": "Førskolepedagogikk",
    "23011": "Førskolepedagogikk ebøker",
    "23012": "Førskolepedagogikk lydbøker",
    "23020": "Spesialpedagogikk",
    "23021": "Spesialpedagogikk ebøker",
    "23022": "Spesialpedagogikk lydbøker",
    "23030": "Generell pedagogikk",
    "23031": "Generell pedagogikk ebøker",
    "23032": "Generell pedagogikk lydbøker",
    "23040": "Psykologi",
    "23041": "Psykologi ebøker",
    "23042": "Psykologi lydbøker",
    "23090": "Pedagogikk / psykologi tilbud",
    "23091": "Pedagogikk/psykologi tilbud ebøker",
    "23092": "Pedagogikk/psykologi tilbud lydbøker",
    "23500": "Helse- og sosialfag, diverse",
    "23501": "Helse- og sosialfag, diverse ebøker",
    "23502": "Helse- og sosialfag, diverse lydbøker",
    "23510": "Medisin",
    "23511": "Medisin ebøker",
    "23512": "Medisin lydbøker",
    "23520": "Sykepleie",
    "23521": "Sykepleie ebøker",
    "23522": "Sykepleie lydbøker",
    "23530": "Odontologi",
    "23531": "Odontologi ebøker",
    "23532": "Odontologi lydbøker",
    "23540": "Sosialt arbeid",
    "23541": "Sosialt arbeid ebøker",
    "23542": "Sosialt arbeid lydbøker",
    "23550": "Psykiatri",
    "23551": "Psykiatri ebøker",
    "23552": "Psykiatri lydbøker",
    "23560": "Fysioterapi",
    "23561": "Fysioterapi ebøker",
    "23562": "Fysioterapi lydbøker",
    "23570": "Farmasi",
    "23571": "Farmasi ebøker",
    "23572": "Farmasi lydbøker",
    "23580": "Ernæringslære",
    "23581": "Ernæringslære ebøker",
    "23582": "Ernæringslære lydbøker",
    "23590": "Helse og sosialfag tilbud",
    "23591": "Helse og sosialfag tilbud ebøker",
    "23592": "Helse og sosialfag tilbud lydbøker",
    "24000": "Samfunnsvitens. fag, diverse",
    "24001": "Samfunnsvitens. fag, diverse ebøker",
    "24002": "Samfunnsvitens. fag, diverse lydbøker",
    "24010": "Sosiologi",
    "24011": "Sosiologi ebøker",
    "24012": "Sosiologi lydbøker",
    "24020": "Statsvitenskap / politikk / forvaltning",
    "24021": "Statsvitenskap / politikk / forv. ebøker",
    "24022": "Statsvitenskap / politikk / forv. lydbøker",
    "24030": "Sosialantropologi",
    "24031": "Sosialantropologi ebøker",
    "24032": "Sosialantropologi lydbøker",
    "24040": "Medie- og kommunikasjon",
    "24041": "Medie- og kommunikasjon ebøker",
    "24042": "Medie- og kommunikasjon lydbøker",
    "24050": "Samfunnsgeografi",
    "24051": "Samfunnsgeografi ebøker",
    "24052": "Samfunnsgeografi lydbøker",
    "24060": "Samfunnsfag (metode)",
    "24061": "Samfunnsfag (metode) ebøker",
    "24062": "Samfunnsfag (metode) lydbøker",
    "24090": "Samfunnsvitenskapelige fag tilbud",
    "24091": "Samfunnsvitens. fag tilbud ebøker",
    "24092": "Samfunnsvitens. fag tilbud lydbøker",
    "24500": "Språk / litteratur, diverse",
    "24501": "Språk / litteratur, diverse ebøker",
    "24502": "Språk / litteratur, diverse lydbøker",
    "24510": "Språkvitenskap",
    "24511": "Språkvitenskap ebøker",
    "24512": "Språkvitenskap lydbøker",
    "24520": "Litteraturvitenskap",
    "24521": "Litteraturvitenskap ebøker",
    "24522": "Litteraturvitenskap lydbøker",
    "24530": "Språklære (grammatikk, språkkurs...)",
    "24531": "Språklære (grammatikk, språkkurs) ebøker",
    "24532": "Språklære (grammatikk, språkkurs) lydbøker",
    "24540": "Litterære tekster",
    "24541": "Litterære tekster ebøker",
    "24542": "Litterære tekster lydbøker",
    "24550": "Norsk som fremmedspråk",
    "24551": "Norsk som fremmedspråk ebøker",
    "24552": "Norsk som fremmedspråk lydbøker",
    "24560": "Litteraturhistorie",
    "24561": "Litteraturhistorie ebøker",
    "24562": "Litteraturhistorie lydbøker",
    "24590": "Språk tilbud",
    "24591": "Språk tilbud ebøker",
    "24592": "Språk tilbud lydbøker",
    "25500": "Religion / historie / filosofi, diverse",
    "25501": "Religion / historie / filos. div. ebøker",
    "25502": "Religion / historie / filos. div. lydbøker",
    "25510": "Religion / teologi",
    "25511": "Religion / teologi ebøker",
    "25512": "Religion / teologi lydbøker",
    "25520": "Filosofi / idéhistorie",
    "25521": "Filosofi / idéhistorie ebøker",
    "25522": "Filosofi / idéhistorie lydbøker",
    "25530": "ExPhil. / ExFac.",
    "25531": "ExPhil. / ExFac. ebøker",
    "25532": "ExPhil. / ExFac. lydbøker",
    "25540": "Etnologi / folkloristikk",
    "25541": "Etnologi / folkloristikk ebøker",
    "25542": "Etnologi / folkloristikk lydbøker",
    "25550": "Historie",
    "25551": "Historie ebøker",
    "25552": "Historie lydbøker",
    "25560": "Arkeologi",
    "25561": "Arkeologi ebøker",
    "25562": "Arkeologi lydbøker",
    "25590": "Religion, historie, filosofi tilbud",
    "25591": "Religion,historie,filosofi tilbud ebøker",
    "25592": "Religion,historie,filosofi tilbud lydbøker",
    "26000": "Data, diverse",
    "26001": "Data, diverse ebøker",
    "26002": "Data, diverse lydbøker",
    "26010": "Internett",
    "26011": "Internett ebøker",
    "26012": "Internett lydbøker",
    "26020": "Nettverk",
    "26021": "Nettverk ebøker",
    "26022": "Nettverk lydbøker",
    "26030": "Operativsystemer",
    "26031": "Operativsystemer ebøker",
    "26032": "Operativsystemer lydbøker",
    "26040": "Administrative programmer",
    "26041": "Administrative programmer ebøker",
    "26042": "Administrative programmer lydbøker",
    "26050": "Databaser",
    "26051": "Databaser ebøker",
    "26052": "Databaser lydbøker",
    "26060": "Grafikk",
    "26061": "Grafikk ebøker",
    "26062": "Grafikk lydbøker",
    "26070": "Programmering",
    "26071": "Programmering ebøker",
    "26072": "Programmering lydbøker",
    "26090": "Data tilbud",
    "26091": "Data tilbud ebøker",
    "26092": "Data tilbud lydbøker",
    "26500": "Tekniske fag, diverse",
    "26501": "Tekniske fag, diverse ebøker",
    "26502": "Tekniske fag, diverse lydbøker",
    "26510": "Maskin / mekanikk",
    "26511": "Maskin / mekanikk ebøker",
    "26512": "Maskin / mekanikk lydbøker",
    "26520": "Elektro / energi",
    "26521": "Elektro / energi ebøker",
    "26522": "Elektro / energi lydbøker",
    "26530": "Telekommunikasjon",
    "26531": "Telekommunikasjon ebøker",
    "26532": "Telekommunikasjon lydbøker",
    "26540": "Bygg",
    "26541": "Bygg ebøker",
    "26542": "Bygg lydbøker",
    "26550": "Miljøteknikk",
    "26551": "Miljøteknikk ebøker",
    "26552": "Miljøteknikk lydbøker",
    "26560": "Marinteknikk",
    "26561": "Marinteknikk ebøker",
    "26562": "Marinteknikk lydbøker",
    "26570": "Oljeteknologi",
    "26571": "Oljeteknologi ebøker",
    "26572": "Oljeteknologi lydbøker",
    "26580": "Industri / transport / servicenæring",
    "26581": "Industri / transport / servicen. ebøker",
    "26582": "Industri / transport / servicen. lydbøker",
    "26590": "Tekniske fag tilbud",
    "26591": "Tekniske fag tilbud ebøker",
    "26592": "Tekniske fag tilbud lydbøker",
    "27000": "Matematikk / naturvitenskap, diverse",
    "27001": "Matematikk, naturvit., diverse ebøker",
    "27002": "Matematikk, naturvit., diverse lydbøker",
    "27010": "Matematikk",
    "27011": "Matematikk ebøker",
    "27012": "Matematikk lydbøker",
    "27015": "Astronomi",
    "27016": "Astronomi ebøker",
    "27017": "Astronomi lydbøker",
    "27020": "Biologi",
    "27021": "Biologi ebøker",
    "27022": "Biologi lydbøker",
    "27030": "Botanikk",
    "27031": "Botanikk ebøker",
    "27032": "Botanikk lydbøker",
    "27040": "Fysikk",
    "27041": "Fysikk ebøker",
    "27042": "Fysikk lydbøker",
    "27050": "Geografi",
    "27051": "Geografi ebøker",
    "27052": "Geografi lydbøker",
    "27060": "Geologi",
    "27061": "Geologi ebøker",
    "27062": "Geologi lydbøker",
    "27070": "Kjemi",
    "27071": "Kjemi ebøker",
    "27072": "Kjemi lydbøker",
    "27080": "Zoologi",
    "27081": "Zoologi ebøker",
    "27082": "Zoologi lydbøker",
    "27090": "Matematikk, naturvit. Tilbud",
    "27091": "Matematikk, naturvit. Tilbud ebøker",
    "27092": "Matematikk, naturvit. Tilbud lydbøker",
    "27500": "Primærnæringer, diverse",
    "27501": "Primærnæringer, diverse ebøker",
    "27502": "Primærnæringer, diverse lydbøker",
    "27510": "Landbruk / skogbruk",
    "27511": "Landbruk / skogbruk ebøker",
    "27512": "Landbruk / skogbruk lydbøker",
    "27520": "Fiske / sjøfart",
    "27521": "Fiske / sjøfart ebøker",
    "27522": "Fiske / sjøfart lydbøker",
    "27590": "Primærnæringer, tilbud",
    "27591": "Primærnæringer, tilbud ebøker",
    "27592": "Primærnæringer, tilbud lydbøker",
    "31000": "Mat og drikke, diverse",
    "31001": "Mat og drikke, diverse  ebøker",
    "31002": "Mat og drikke, diverse  lydbøker",
    "31010": "Kokebøker",
    "31011": "Kokebøker ebøker",
    "31012": "Kokebøker lydbøker",
    "31020": "Mat fra andre land",
    "31021": "Mat fra andre land ebøker",
    "31022": "Mat fra andre land lydbøker",
    "31030": "Drikke",
    "31031": "Drikke ebøker",
    "31032": "Drikke lydbøker",
    "31090": "Mat og drikke, tilbud",
    "31091": "Mat og drikke, tilbud ebøker",
    "31092": "Mat og drikke, tilbud lydbøker",
    "32000": "Reise, diverse",
    "32001": "Reise, diverse ebøker",
    "32002": "Reise, diverse lydbøker",
    "32010": "Amerika",
    "32011": "Amerika ebøker",
    "32012": "Amerika lydbøker",
    "32020": "Europa",
    "32021": "Europa ebøker",
    "32022": "Europa lydbøker",
    "32030": "Asia",
    "32031": "Asia ebøker",
    "32032": "Asia lydbøker",
    "32040": "Afrika",
    "32041": "Afrika ebøker",
    "32042": "Afrika lydbøker",
    "32050": "Australia",
    "32051": "Australia ebøker",
    "32052": "Australia lydbøker",
    "32060": "Reiseskildringer",
    "32061": "Reiseskildringer ebøker",
    "32062": "Reiseskildringer lydbøker",
    "32070": "Atlas",
    "32071": "Atlas ebøker",
    "32072": "Atlas lydbøker",
    "32090": "Reise tilbud",
    "32091": "Reise tilbud ebøker",
    "32092": "Reise tilbud lydbøker",
    "32500": "Turistbøker Norge, diverse",
    "32501": "Turistbøker Norge, diverse ebøker",
    "32502": "Turistbøker Norge, diverse lydbøker",
    "32510": "Billedbøker om Norge",
    "32511": "Billedbøker om Norge ebøker",
    "32512": "Billedbøker om Norge lydbøker",
    "32520": "Troll",
    "32521": "Troll ebøker",
    "32522": "Troll lydbøker",
    "32530": "Turguider",
    "32531": "Turguider ebøker",
    "32532": "Turguider lydbøker",
    "32590": "Turistbøker Norge tilbud",
    "32591": "Turistbøker Norge tilbud ebøker",
    "32592": "Turistbøker Norge tilbud lydbøker",
    "33000": "Sport og fritid, diverse",
    "33001": "Sport og fritid, diverse ebøker",
    "33002": "Sport og fritid, diverse lydbøker",
    "33010": "Maritimt",
    "33011": "Maritimt ebøker",
    "33012": "Maritimt lydbøker",
    "33020": "Jakt / våpen / fiske",
    "33021": "Jakt / våpen / fiske ebøker",
    "33022": "Jakt / våpen / fiske lydbøker",
    "33030": "Friluft",
    "33031": "Friluft ebøker",
    "33032": "Friluft lydbøker",
    "33040": "Kampsport",
    "33041": "Kampsport ebøker",
    "33042": "Kampsport lydbøker",
    "33050": "Vintersport",
    "33051": "Vintersport ebøker",
    "33052": "Vintersport lydbøker",
    "33060": "Ballsport",
    "33061": "Ballsport ebøker",
    "33062": "Ballsport lydbøker",
    "33070": "Golf",
    "33071": "Golf ebøker",
    "33072": "Golf lydbøker",
    "33080": "Fritid",
    "33081": "Fritid ebøker",
    "33082": "Fritid lydbøker",
    "33090": "Sport fritid tilbud",
    "33091": "Sport fritid tilbud ebøker",
    "33092": "Sport fritid tilbud lydbøker",
    "34000": "Dokumentar, diverse",
    "34001": "Dokumentar, diverse ebøker",
    "34002": "Dokumentar, diverse lydbøker",
    "34010": "Biografier / memoarer",
    "34011": "Biografier / memoarer ebøker",
    "34012": "Biografier / memoarer lydbøker",
    "34020": "Debatt / samfunn",
    "34021": "Debatt / samfunn ebøker",
    "34022": "Debatt / samfunn lydbøker",
    "34030": "Historie",
    "34031": "Historie ebøker",
    "34032": "Historie lydbøker",
    "34040": "Filosofi",
    "34041": "Filosofi ebøker",
    "34042": "Filosofi lydbøker",
    "34050": "Lokalt utgitte bøker",
    "34051": "Lokalt utgitte bøker ebøker",
    "34052": "Lokalt utgitte bøker lydbøker",
    "34060": "Økonomi / arbeidsliv",
    "34061": "Økonomi / arbeidsliv ebøker",
    "34062": "Økonomi / arbeidsliv lydbøke",
    "34090": "Dokumentar tilbud",
    "34091": "Dokumentar tilbud ebøker",
    "34092": "Dokumentar tilbud lydbøker",
    "35000": "Natur, diverse",
    "35001": "Natur, diverse ebøker",
    "35002": "Natur, diverse lydbøker",
    "35010": "Katter",
    "35011": "Katter ebøker",
    "35012": "Katter lydbøker",
    "35020": "Hunder",
    "35021": "Hunder ebøker",
    "35022": "Hunder lydbøker",
    "35030": "Hester",
    "35031": "Hester ebøker",
    "35032": "Hester lydbøker",
    "35040": "Fugler",
    "35041": "Fugler ebøker",
    "35042": "Fugler lydbøker",
    "35050": "Andre dyr",
    "35051": "Andre dyr ebøker",
    "35052": "Andre dyr lydbøker",
    "35060": "Flora",
    "35061": "Flora ebøker",
    "35062": "Flora lydbøker",
    "35070": "Geologi",
    "35071": "Geologi ebøker",
    "35072": "Geologi lydbøker",
    "35080": "Naturvitenskap",
    "35081": "Naturvitenskap ebøker",
    "35082": "Naturvitenskap lydbøker",
    "35090": "Natur tilbud",
    "35091": "Natur tilbud ebøker",
    "35092": "Natur tilbud lydbøker",
    "36000": "Forming / håndarbeid, diverse",
    "36001": "Forming / håndarbeid, diverse ebøker",
    "36002": "Forming / håndarbeid, diverse lydbøker",
    "36010": "Søm",
    "36011": "Søm ebøker",
    "36012": "Søm lydbøker",
    "36020": "Male / tegne",
    "36021": "Male / tegne ebøker",
    "36022": "Male / tegne lydbøker",
    "36030": "Håndarbeid",
    "36031": "Håndarbeid ebøker",
    "36032": "Håndarbeid lydbøker",
    "36090": "Forming / håndarbeid, tilbud",
    "36091": "Forming/håndarbeid, tilbud ebøker",
    "36092": "Forming/håndarbeid, tilbud lydbøker",
    "36500": "Hus og hage, diverse",
    "36501": "Hus og hage, diverse ebøker",
    "36502": "Hus og hage, diverse lydbøker",
    "36510": "Innredning / vedlikehold",
    "36511": "Innredning / vedlikehold ebøker",
    "36512": "Innredning / vedlikehold lydbøker",
    "36520": "Hage / planter",
    "36521": "Hage / planter ebøker",
    "36522": "Hage / planter lydbøker",
    "36590": "Hus og hage tilbud",
    "37000": "Livssyn / religion / mytologi, diverse",
    "37001": "Livssyn / religion / mytol. div. ebøker",
    "37002": "Livssyn / religion / mytol. div. lydbøker",
    "37010": "Kristendom",
    "37011": "Kristendom ebøker",
    "37012": "Kristendom lydbøker",
    "37020": "Andre religioner",
    "37021": "Andre religioner ebøker",
    "37022": "Andre religioner lydbøker",
    "37090": "Livssyn, tilbud",
    "37091": "Livssyn, tilbud ebøker",
    "37092": "Livssyn, tilbud lydbøker",
    "37500": "Alternativ livsstil, diverse",
    "37501": "Alternativ livsstil, diverse ebøker",
    "37502": "Alternativ livsstil, diverse lydbøker",
    "37510": "Astrologi",
    "37511": "Astrologi ebøker",
    "37512": "Astrologi lydbøker",
    "37520": "Selvutvikling",
    "37521": "Selvutvikling ebøker",
    "37522": "Selvutvikling lydbøker",
    "37530": "Spiritualitet",
    "37531": "Spiritualitet ebøker",
    "37532": "Spiritualitet lydbøker",
    "37590": "Alt livsstil, tilbud",
    "37591": "Alt livsstil, tilbud ebøker",
    "37592": "Alt livsstil, tilbud lydbøker",
    "38000": "Kunst og kultur, diverse",
    "38001": "Kunst og kultur, diverse ebøker",
    "38002": "Kunst og kultur, diverse lydbøker",
    "38010": "Kunstmonografier / teori / historie",
    "38011": "Kunstmonogr. / teori / historie ebøker",
    "38012": "Kunstmonogr. / teori / historie lydbøker",
    "38020": "Foto / film, kunst og kultur",
    "38021": "Foto / film, kunst og kultur ebøker",
    "38022": "Foto / film, kunst og kultur lydbøker",
    "38030": "Musikk",
    "38031": "Musikk ebøker",
    "38032": "Musikk lydbøker",
    "38040": "Arkitektur",
    "38041": "Arkitektur ebøker",
    "38042": "Arkitektur lydbøker",
    "38050": "Design",
    "38051": "Design ebøker",
    "38052": "Design lydbøker",
    "38060": "Interiør / antikviteter / kunsthåndverk",
    "38061": "Interiør / antikv. / kunsthåndv. ebøker",
    "38062": "Interiør / antikv. / kunsthåndv. lydbøker",
    "38070": "Scenekunst",
    "38071": "Scenekunst ebøker",
    "38072": "Scenekunst lydbøker",
    "38080": "Kulturhistorie",
    "38081": "Kulturhistorie ebøker",
    "38082": "Kulturhistorie lydbøker",
    "38090": "Kunst og kultur. Tilbud",
    "38091": "Kunst og kultur, tilbud ebøker",
    "38092": "Kunst og kultur, tilbud lydbøker",
    "38500": "Teknikk / populærvitenskap, diverse",
    "38501": "Teknikk / populærvit., diverse ebøker",
    "38502": "Teknikk / populærvit., diverse lydbøker",
    "38510": "Foto / film / video, teknikker",
    "38511": "Foto / film / video, teknikker ebøker",
    "38512": "Foto / film / video, teknikker lydbøker",
    "38520": "Bil / båt / fly / tog etc.",
    "38521": "Bil / båt / fly / tog etc. ebøker",
    "38522": "Bil / båt / fly / tog etc. lydbøker",
    "38530": "Astronomi / fysikk / kjemi",
    "38531": "Astronomi / fysikk / kjemi ebøker",
    "38532": "Astronomi / fysikk / kjemi lydbøker",
    "38590": "Teknikk / populærvit., tilbud",
    "38591": "Teknikk/ populærvit., tilbud ebøker",
    "38592": "Teknikk/ populærvit., tilbud lydbøker",
    "39000": "Familie og helse, diverse",
    "39001": "Familie og helse, diverse ebøker",
    "39002": "Familie og helse, diverse lydbøker",
    "39010": "Medisin / sykdommer",
    "39011": "Medisin / sykdommer ebøker",
    "39012": "Medisin / sykdommer lydbøker",
    "39020": "Sex og samliv",
    "39021": "Sex og samliv ebøker",
    "39022": "Sex og samliv lydbøker",
    "39030": "Svangerskap / fødsel / barn",
    "39031": "Svangerskap / fødsel / barn ebøker",
    "39032": "Svangerskap / fødsel / barn lydbøker",
    "39040": "Kosthold / diett",
    "39041": "Kosthold / diett ebøker",
    "39042": "Kosthold / diett lydbøker",
    "39062": "Mental helse lydbøker",
    "39090": "Familie og helse, tilbud",
    "39091": "Familie og helse, tilbud ebøker",
    "39092": "Familie og helse, tilbud lydbøker",
    "39500": "Ordbøker, diverse",
    "39501": "Ordbøker, diverse ebøker",
    "39502": "Ordbøker, diverse lydbøker",
    "39510": "Norsk / nordiske ordbøker",
    "39511": "Norsk / nordiske ordbøker ebøker",
    "39512": "Norsk / nordiske ordbøker lydbøker",
    "39530": "Engelsk / amerikanske ordbøker",
    "39531": "Engelsk / amerikanske ordbøker ebøker",
    "39532": "Engelsk / amerikanske ordbøker lydbøker",
    "39540": "Franske ordbøker",
    "39541": "Franske ordbøker ebøker",
    "39542": "Franske ordbøker lydbøker",
    "39550": "Tyske ordbøker",
    "39551": "Tyske ordbøker ebøker",
    "39552": "Tyske ordbøker lydbøker",
    "39560": "Spanske ordbøker",
    "39561": "Spanske ordbøker ebøker",
    "39562": "Spanske ordbøker lydbøker",
    "39570": "Andre språks ordbøker",
    "39571": "Andre språks ordbøker ebøker",
    "39572": "Andre språks ordbøker lydbøker",
    "39585": "Kryssordbøker",
    "39586": "Kryssordbøker ebøker",
    "39587": "Kryssordbøker lydbøker",
    "39590": "Ordbøker, tilbud",
    "39591": "Ordbøker, tilbud ebøker",
    "39592": "Ordbøker, tilbud lydbøker",
    "41000": "Romaner, diverse",
    "41001": "Romaner, diverse ebøker",
    "41002": "Romaner, diverse lydbøker",
    "41010": "Romaner",
    "41011": "Romaner ebøker",
    "41012": "Romaner lydbøker",
    "41020": "Romaner kartongisert",
    "41030": "Romaner heftet",
    "41040": "Romanserier",
    "41041": "Romanserier ebøker",
    "41042": "Romanserier lydbøker",
    "41090": "Romaner tilbud",
    "41091": "Romaner tilbud ebøker",
    "41092": "Romaner tilbud lydbøker",
    "42000": "Lyrikk og drama, diverse",
    "42001": "Lyrikk og drama, diverse ebøker",
    "42002": "Lyrikk og drama, diverse lydbøker",
    "42010": "Lyrikk,  norsk og oversatt",
    "42011": "Lyrikk, norsk og oversatt ebøker",
    "42012": "Lyrikk, norsk og oversatt lydbøker",
    "42020": "Drama, norsk og oversatt",
    "42021": "Drama, norsk og oversatt ebøker",
    "42022": "Drama, norsk og oversatt lydbøker",
    "42030": "Sitatbøker / ordspråk",
    "42031": "Sitatbøker / ordspråk ebøker",
    "42032": "Sitatbøker / ordspråk lydbøker",
    "42090": "Lyrikk / drama tilbud",
    "42091": "Lyrikk / drama tilbud ebøker",
    "42092": "Lyrikk / drama tilbud lydbøker",
    "43000": "Krim / spenning, diverse",
    "43001": "Krim / spenning, diverse ebøker",
    "43002": "Krim / spenning, diverse lydbøker",
    "43010": "Krim / spenning",
    "43011": "Krim / spenning ebøker",
    "43012": "Krim / spenning lydbøker",
    "43020": "Krim / spenning kartongisert",
    "43030": "Krim / spenning heftet",
    "43090": "Krim / spenning tilbud",
    "43091": "Krim / spenning tilbud ebøker",
    "43092": "Krim / spenning tilbud lydbøker",
    "44000": "Fantasy / science fiction, diverse",
    "44001": "Fantasy / science fiction, div. ebøker",
    "44002": "Fantasy / science fiction, div. lydbøker",
    "44010": "Fantasy / science fiction",
    "44011": "Fantasy / science fiction ebøker",
    "44012": "Fantasy / science fiction lydbøker",
    "44020": "Fantasy / science fiction kartongisert",
    "44030": "Fantasy / science fiction heftet",
    "44040": "Rollespill",
    "44041": "Rollespill ebøker",
    "44042": "Rollespill lydbøker",
    "44090": "Fantasy / science fiction tilbud",
    "44091": "Fantasy / science fiction tilbud ebøker",
    "44092": "Fantasy / science fiction tilbud lydbøker",
    "45000": "Humor / tegneserier, diverse",
    "45001": "Humor / tegneserier, diverse ebøker",
    "45002": "Humor / tegneserier, diverse lydbøker",
    "45010": "Humor",
    "45011": "Humor ebøker",
    "45012": "Humor lydbøker",
    "45020": "Tegneserier",
    "45021": "Tegneserier ebøker",
    "45022": "Tegneserier lydbøker",
    "45030": "Grafiske romaner / manga for voksne",
    "45031": "Grafiske romaner / manga for voksne ebøker",
    "45032": "Grafiske romaner for voksne /manga lydbøker",
    "45090": "Humor / tegneserier tilbud",
    "45091": "Humor / tegneserier tilbud ebøker",
    "45092": "Humor / tegneserier tilbud lydbøker",
    "46000": "Barnebøker, diverse",
    "46001": "Barnebøker, diverse ebøker",
    "46002": "Barnebøker, diverse lydbøker",
    "46010": "0-2 år Barnets første bøker - pekebøker",
    "46011": "0-2 år Barnets første bøker - ebøker",
    "46012": "0-2 år Barnets første bøker - lydbøker",
    "46020": "2 + Billedbøker",
    "46021": "2 + Billedbøker ebøker",
    "46022": "2 + Lydbøker",
    "46030": "4 + Høytlesningsbøker, billedbøker",
    "46031": "4 + Høytlesningsbøker, billedbøk. ebøker",
    "46032": "4 + Lydbøker",
    "46040": "6 + Billedbøker, høytlesning, lese selv",
    "46041": "6 + Billedbøker, høytlesning ebøker",
    "46042": "6 + Lydbøker",
    "46050": "8 + Tekstbøker",
    "46051": "8 + Tekstbøker ebøker",
    "46052": "8 + Lydbøker",
    "46060": "10 + Tekstbøker",
    "46061": "10 + Tekstbøker ebøker",
    "46062": "10 + Lydbøker",
    "46070": "Eventyr, fabler, epos",
    "46071": "Eventyr ebøker",
    "46072": "Eventyr lydbøker",
    "46080": "Sangbøker / rim og regler / barnebibler",
    "46081": "Sangb. / rim, regler / barnebibl. ebøker",
    "46082": "Sangb. / rim, regler / barnebibl. lybøker",
    "46090": "Barnebøker skjønnlitteratur. Tilbud",
    "46091": "Barnebøker skjønnlitt. tilbud ebøker",
    "46092": "Barnebøker skjønnlitt. tilbud lydbøker",
    "46500": "Barnebøker fakta, diverse",
    "46501": "Barnebøker fakta, diverse ebøker",
    "46502": "Barnebøker fakta, diverse lydbøker",
    "46510": "4 + Enkle faktabøker",
    "46511": "4 + Enkle faktabøker ebøker",
    "46512": "4 + Enkle faktabøker lydbøker",
    "46520": "6 + Faktabøker",
    "46521": "6 + Faktabøker ebøker",
    "46522": "6 + Faktabøker lydbøker",
    "46530": "8 + Faktabøker",
    "46531": "8 + Faktabøker ebøker",
    "46532": "8 + Faktabøker lydbøker",
    "46540": "10 + Faktabøker",
    "46541": "10 + Faktabøker ebøker",
    "46542": "10 + Faktabøker lydbøker",
    "46550": "Spørrebøker, gåter, vitser og leker",
    "46551": "Spørrebøker, gåter, vitser, leker ebøker",
    "46552": "Spørrebøker, gåter, vitser, leker lydbøker",
    "46590": "Faktabøker for barn tilbud",
    "46591": "Faktabøker for barn tilbud ebøker",
    "46592": "Faktabøker for barn tilbud lydbøker",
    "47000": "Ungdomsbøker, diverse",
    "47001": "Ungdomsbøker, diverse ebøker",
    "47002": "Ungdomsbøker, diverse lydbøker",
    "47010": "Ungdomsbøker",
    "47011": "Ungdomsbøker ebøker",
    "47012": "Ungdomsbøker lydbøker",
    "47020": "Ungdomsserier",
    "47021": "Ungdomsserier ebøker",
    "47022": "Ungdomsserier lydbøker",
    "47090": "Ungdomsbøker tilbud",
    "47091": "Ungdomsbøker tilbud ebøker",
    "47092": "Ungdomsbøker tilbud lydbøker",
    "49000": "Utenlandsk skjønnlitteratur, diverse",
    "49001": "Utenlandsk skjønnlitteratur, div. ebøker",
    "49002": "Utenlandsk skjønnlitteratur, div. lydbøker",
    "49010": "Romaner, utenlandske",
    "49011": "Romaner, utenlandske ebøker",
    "49012": "Romaner, utenlandske lydbøker",
    "49020": "Krim / spenning, utenlandsk",
    "49021": "Krim / spenning, utenlandsk ebøker",
    "49022": "Krim / spenning, utenlandsk lydbøker",
    "49030": "Fantasy / science fiction, utenlandsk",
    "49031": "Fantasy / science fiction utenl. ebøker",
    "49032": "Fantasy / science fiction utenl. lydbøker",
    "49040": "Rollespill, utenlandsk",
    "49041": "Rollespill, utenlandsk ebøker",
    "49042": "Rollespill, utenlandsk lydbøker",
    "49050": "Lyrikk / drama, utenlandsk",
    "49051": "Lyrikk / drama, utenlandsk ebøker",
    "49052": "Lyrikk / drama, utenlandsk lydbøker",
    "49090": "Utenlandsk skjønnlitteratur, tilbud",
    "49091": "Utenlandsk skjønnlitt. tilbud ebøker",
    "49092": "Utenlandsk skjønnlitt. tilbud lydbøker",
    "49500": "Verk, diverse",
    "49501": "Verk, diverse ebøker",
    "49502": "Verk, diverse lydbøker",
    "49510": "Verk, leksika",
    "49511": "Verk, leksika ebøker",
    "49512": "Verk, leksika lydbøker",
    "49520": "Verk, skjønnlitteratur",
    "49521": "Verk, skjønnlitteratur ebøker",
    "49522": "Verk, skjønnlitteratur lydbøker",
    "49530": "Verk, historie",
    "49531": "Verk, historie ebøker",
    "49532": "Verk, historie lydbøker",
    "49540": "Verk, barn",
    "49541": "Verk, barn ebøker",
    "49542": "Verk, barn lydbøker",
    "49590": "Verk, tilbud",
    "49591": "Verk, tilbud ebøker",
    "49592": "Verk, tilbud lydbøker",
    "50020": "Registre og skilleblad",
    "51500": "Emballasje, diverse",
    "52500": "Etiketter, diverse",
    "54000": "Blokker og formularer, diverse",
    "55000": "Kalendermateriell, diverse",
    "55010": "Tidsplanleggere",
    "55020": "Almanakker og kalendere",
    "55021": "Dagbøker og avtalebøker",
    "55022": "Lommekalendere",
    "55023": "Veggkalendere",
    "55024": "Bordkalendere",
    "55025": "Planleggingskalendere",
    "55026": "Kunst- og billedkalendere",
    "55027": "Skolekalendere og skoledagbøker",
    "58000": "Data software CD-ROM / DVD, diverse",
    "58010": "Programvare, CD-ROM / DVD",
    "58021": "Spill, CD-ROM / DVD",
    "58022": "Lek og lær, CD-ROM / DVD",
    "58023": "Fakta og fritid, CD-ROM / DVD",
    "58024": "Opplæring, CD-ROM / DVD",
    "58025": "Oppslagsverk, CD-ROM / DVD",
    "58090": "Data software, tilbud",
    "63000": "Skolemateriell, diverse",
    "63500": "Formingsprodukter, diverse",
    "64000": "Leketøy, diverse",
    "64011": "Babyleker",
    "64015": "Mykdyr",
    "64500": "Andre barneprodukter, diverse",
    "64530": "Hobbybøker",
    "64540": "Tegne / malebøker",
    "64550": "Minnebøker / dagbøker",
    "65000": "Spill, diverse",
    "65010": "Puslespill",
    "65020": "Barnespill",
    "65030": "Familiespill",
    "65040": "Elektroniske spill",
    "65050": "Rollespill",
    "65060": "Spill, voksen",
    "66000": "Video / DVD, diverse",
    "66010": "Video barn",
    "66015": "Video, voksen drama",
    "66020": "Video, voksen action / thriller",
    "66025": "Video, voksen komedie",
    "66030": "Video musikk",
    "66040": "Video import",
    "66050": "DVD barn",
    "66055": "DVD voksen drama",
    "66060": "DVD voksen action / thriller",
    "66065": "DVD voksen komedie",
    "66070": "DVD musikk",
    "66075": "DVD diverse",
    "66080": "Laserdisc",
    "66085": "Video uinnspilt",
    "66090": "Video / DVD, tilbud",
    "66500": "Kort, diverse",
    "67010": "Brevpapir",
    "67015": "Brevpapir barn",
    "67500": "Album og memoarbøker, diverse",
    "67530": "Memoarbøker",
    "70000": "Plakater og bilder, diverse",
    "70020": "Posters og bilder",
    "71500": "Kart og globuser, diverse",
    "71510": "Topografiske kart / turkart",
    "71520": "Kart, bilkart, bykart - Norge",
    "71530": "Kart, bilkart, bykart - utland",
    "71540": "Sjøkart",
    "71550": "Globuser",
    "71590": "Kart og globuser, tilbud",
    "74000": "Trend / fancyvarer, diverse",
    "76000": "Boktilbehør, diverse",
    "76020": "Lesebrett",
    "82000": "Musikk, diverse",
    "82010": "CD pop og rock",
    "82020": "CD jazz og klassisk",
    "82025": "CD danseband",
    "82030": "CD singler",
    "82040": "CD barn",
    "82050": "DVD audio",
    "82080": "MC (kassetter)",
    "82090": "Musikk, tilbud",
    "85000": "Magasin / blader, diverse",
    "85010": "Ukeblad",
    "85020": "Magasin",
    "85030": "Tidsskrifter",
    "85040": "Tegneserier",
    "85050": "Magasin / blader, tilbud",
    "90000": "Katalog og brosjyremat. - kontorvarer",
}

SubjectSchemeID43 = {
    "BA": "Bygg- og anleggsteknikk",
    "DH": "Design og håndverk",
    "EL": "Elektrofag",
    "HS": "Helse- og oppvekstfag",
    "ID": "Idrettsfag",
    "MK": "Medier og kommunikasjon",
    "MD": "Musikk, dans og drama",
    "NA": "Naturbruk",
    "RM": "Restaurant- og matfag",
    "SS": "Service og samferdsel",
    "SU": "Studieforberedende utdanningsprogram",
    "ST": "Studiespesialisering",
    "TP": "Teknikk og industriell produksjon",
    "YU": "Yrkesfaglige utdanningsprogram"
}

SubjectSchemeID45 = {
    "1": "Alternative grunnbøker",
    "2": "Arbeidsbøker",
    "3": "Digitale læremidler",
    "4": "Fasiter",
    "5": "Grammatikk",
    "6": "Grunnbøker",
    "7": "Hjelp/støtte",
    "8": "Kart og atlas",
    "9": "Lesetrening",
    "10": "Lettlest",
    "11": "Lovsamlinger",
    "12": "Lyd Bilde It",
    "13": "Lærerveiledninger",
    "14": "Nettsteder",
    "15": "Ordbøker",
    "16": "Ordlister",
    "17": "Tabeller",
    "18": "Tilleggslitteratur",
    "19": "Treningsmateriell",
    "20": "Lærerressurser",
    "21": "Lydbøker",
    "22": "Tavleressurser",
}

AudienceCodeType = {
    "02": "Proprietary"
}

PublisherRoleCode = {
    "01": "Publisher"
}

PublishingDateRole = {
    "01": "Publication Date",
    "02": "Embargo date",
    "11": "Date of first publication",
    "12": "Last reprint date"
}

SalesRightsTypeCode = {
    "00": "Sales rights unknown or unstated for any reason",
    "01": "For sale with exclusive rights in the specified countries or territories",
    "02": "For sale with non-exclusive rights in the specified countries or territories",
    "03": "Not for sale in the specified countries or territories (reason unspecified)",
    "04": "Not for sale in the specified countries (but publisher holds exclusive rights in those countries or territories)",
    "05": "Not for sale in the specified countries (publisher holds non-exclusive rights in those countries or territories)",
    "06": "Not for sale in the specified countries (because publisher does not hold rights in those countries or territories)",
    "07": "For sale with exclusive rights in the specified countries or territories (sales restriction applies)",
    "08": "For sale with non-exclusive rights in the specified countries or territories (sales restriction applies)",
}

ProductRelationCode = {
    "01": "Includes",
    "02": "Part of",
    "06": "Alternative format",
    "12": "Publisher’s suggested alternative",
}

SalesRestrictionTypeCode = {
    "00": "Unspecified - see text",
    "04": "Retailer exclusive",
    "12": "Not for sale to subscription services",
    "06": "To libraries only",
    "99": "No restrictions on sales",
    "09": "Except to libraries",
    "13": "to subscription services only"
}

MarketPublishingStatus = {
    "00": "Ikke spesifisert",
    "01": "Vil ikke utkomme",
    "02": "Forventes utgitt",
    "03": "Utsatt inntil videre",
    "04": "I salg",
    "05": "Ikke lenger vårt produkt",
    "06": "Utsolgt, til vurdering",
    "07": "Utsolgt",
    "08": "Ikke i ordinært salg",
    "09": "Ukjent",
    "10": "Reservert nedsettelse",
}

MarketPublishingStatusNote = {
    "Grønn": "In sale",
    "Rød": "Out of sale",
    "Gul": "To be pulbished/temporarily out of print"
}

SupplierRole = {
    "06": "Suppliers distributor to retailers"
}

SupplierIdentifierType = {
    "01": "Proprietary",
    "06": "GLN"
}

SupplierCodeType = {
    "01": "Suppliers sales classification"
}

ProductAvailability = {
    "01": "Vil ikke utkomme",
    "10": "Ikke tilgjengelig ennå",
    "11": "Ikke ankommet lager",
    "12": "Ikke tilgjengelig ennå, vil komme som POD",
    "20": "Tilgjengelig",
    "21": "Tilgjengelig på lager",
    "22": "Skaffes på bestilling",
    "23": "POD - Print on demand",
    "30": "Midlertidig ikke tilgjengelig",
    "31": "Midlertidig tomt på lager",
    "32": "Under opptrykk",
    "33": "Nytt opplag ventes",
    "40": "Ikke tilgjengelig fra oss",
    "41": "Erstattet av nytt produkt",
    "42": "Annet format tilgjengelig",
    "43": "Ikke lenger distribuert av oss",
    "44": "Må bestilles direkte fra vareeier",
    "45": "Selges ikke enkeltvis",
    "46": "Tilbakekalt",
    "47": "Reservert nedsettelse",
    "48": "Utsolgt, erstattes av POD",
    "98": "Ukjent, oppdateringer mottas ikke",
    "99": "Kontakt kundetjenesten",
}

PriceType = {
    "02": "RRP Including Tax",
    "42": "Publisher retail price including tax"
}

PriceTypeQualifier = {
    "00": "Unqualified Price",
    "05": "Consumer Price",
    "10": "Library Price",
    "11": "Education price"
}

TaxType = {
    "01": "VAT"
}

TaxRateCode = {
    "S": "Standard Rate",
    "Z": "Zero-rated"
}

CurrencyCode = {
    "DKK": "Danish Krone",
    "EUR": "Euro",
    "GBP": "Pound Sterling",
    "NOK": "Norske kroner",
    "SEK": "Swedish Krona",
}
