name: Make release

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  make_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Get package version
      run: echo "PACKAGE_VERSION=$(python version.py)" >> $GITHUB_ENV

    - name: Make release
      uses: actions/github-script@v6
      with:
        script: |
          try {
              const response = await github.rest.repos.createRelease({
                name: process.env.PACKAGE_VERSION,
                owner: context.repo.owner,
                repo: 'fabel-common-releases',
                tag_name: process.env.PACKAGE_VERSION,
                generate_release_notes: true,
              });
  
              core.exportVariable('RELEASE_ID', response.data.id);
              core.exportVariable('RELEASE_UPLOAD_URL', response.data.upload_url);
            } catch (error) {
              core.setFailed(error.message);
            }
