# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PR

# Controls when the workflow will run
on:
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:    

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get package version
      run: echo "PACKAGE_VERSION=$(python version.py)" >> $GITHUB_ENV

    - name: Verify that package is not a release candidate
      run: ${{ !contains(env.PACKAGE_VERSION, 'rc') }}

    - name: Check for existing release
      uses: actions/github-script@v6
      with:
        script: |
          try {
              const response = await github.rest.repos.getLatestRelease({
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              core.exportVariable('LATEST_RELEASE_TAG', response.data.tag_name);
          } catch (error) {
            if (error.message == 'Not Found') {
              core.exportVariable('NO_RELEASES_EXIST', true);
              return;
            }
            core.setFailed(error.message);
          }

    - name: Verify that release tag does not match latest release
      if: ${{ env.NO_RELEASES_EXIST != 'true' }}
      run: ${{ env.PACKAGE_VERSION != env.LATEST_RELEASE_TAG }}

    - name: Install pipenv
      run: pipx install pipenv

    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        cache: 'pipenv'

    # caching only works with install (not sync)
    - run: pipenv install --dev
    - uses: actions/setup-node@v2

    - name: Lint with flake8
      run: pipenv run flake8

    - name: Check with pyright
      run: pipenv run pyright

    - name: Test with pytest
      run: |
        pipenv run pytest
